apiVersion: v1
kind: Service

metadata:
  name: backend
  labels:
    app: backend
  namespace: prefix

spec:
  selector:
    app: backend
  ports:
    - port: 6757
      targetPort: 6757
      name: http
